# sudo apt-get install docker-compose-plugin
# docker compose up -d --force-recreate

services:
  web:
    image: frontend-app:latest
    container_name: frontend-app
    ports:
      - "3000:3000"

  app:
    image: todo-list:latest
    container_name: todo-list
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
    ports:
      - "8080:8080"

  exchange-rates:
    image: exchange-rates:latest
    container_name: exchange-rates

  db:
    image: mysql:8
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist_db
      MYSQL_USER: todolist_user
      MYSQL_PASSWORD: to_secret_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql