# sudo apt-get install docker-compose-plugin
# docker compose up -d --force-recreate
version: '2'
services:

  db:
    image: mysql:8
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist_db
      MYSQL_USER: todolist_user
      MYSQL_PASSWORD: to_secret_password

    volumes:
      - ./mysql_data:/var/lib/mysql

    networks:
      - uam-network
  
  jenkins:
      image: jenkins/jenkins:lts-jdk17
      privileged: true
      user: root
      ports:
        - '8080:8080'
        - '50000:50000'
      container_name: jenkins
      volumes:
        - jenkins_home:/var/jenkins_home 
        - /var/run/docker.sock:/var/run/docker.sock
      networks:
        - uam-network

volumes:
    jenkins_home:
networks:
  uam-network:
    external: true