# sudo apt-get install docker-compose-plugin
# docker compose up -d --force-recreate
version: '2'
services:

  db:
    image: mysql:8
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist_db
      MYSQL_USER: todolist_user
      MYSQL_PASSWORD: to_secret_password

    volumes:
      - ./mysql_data:/var/lib/mysql

    networks:
      - uam-network

  jenkins:
      image: jenkins/jenkins:lts-jdk17
      privileged: true
      user: root
      ports:
        - '8080:8080'
        - '50000:50000'
      container_name: jenkins
      volumes:
        - jenkins_home:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
      networks:
        - uam-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.3
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - uam-network
  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.3
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    networks:
      - uam-network
  logstash:
    image: docker.elastic.co/logstash/logstash:8.17.3
    ports:
      - '25826:25826'
    volumes:
      - $PWD/logstash_config/:/etc/logstash/conf.d/
      - /var/log/:/var/log/
    command: logstash -f /etc/logstash/conf.d/logstash-spring.conf
    links:
      - "elasticsearch:elasticsearch"
    depends_on:
      - elasticsearch
    networks:
      - uam-network

volumes:
    jenkins_home:
networks:
  uam-network:
    external: true