spring:
  application.name: todolist
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/todolist_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
  sql:
    init:
      mode: always
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
    mode: HTML
    cache: false